### ISSUE TITLE
cdError does actually raise an error

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/libcdms#8]
it should not be void type and return 0/1 so that code calling it can tell the exit(1) is not sufficient for python as a result

```python
import cdtime
cdtime.s2c("whatever")
```

does not fail

**Comment by dnadeau4** [comment]
I got this in Python 2.7
```python
>>> import cdtime
>>> cdtime.s2c("whatever")
CDMS error: Error on character time conversion, string = whatever

0-1-1 0:0:0.0
```

**Comment by doutriaux1** [comment]
yes. The comptime object returned is what I compare in vcs (comparison broken) but really the s2c call should fail it comes from there:  https://github.com/UV-CDAT/libcdms/blob/master/src/db_util/cdTimeConv.c#L246

That is typed `void` should retyped `int` so we can check in Python if it passed or failed

Also: https://github.com/UV-CDAT/libcdms/blob/master/src/db_util/cdUtil.c#L31-L44 is not setting a python error, but it's better to keep it as in w/o involving python here.

**Comment by dnadeau4** [comment]
It fails now.
@doutriaux1 give it a try.
